
name: Release Test 

on:
  # Runs on pushes targeting the default branch
  # push:
  #   branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
         draft: true
         prerelease: true
         allowUpdates: true
         artifacts: "./book.toml"
         tag: "nightly"
